altura = int(input('Digite a altura do triãngulo: '))
base = int(input('Digite a base do triãngulo: '))
area = (base * altura)/2
print('A área do triãngulo é:', area)

raio = float(input('Entre com o valor do raio, para obter a circuferência do círculo: '))

circunferencia = 2 * 3.14 * raio

print("A circuferência do círculo: {:.2f}".format(circunferencia))

lado=a = int(input("Digite o lado do quadrado: ? "))
perimetro  = lado *4
area = lado * lado
print("perimetro:", perimetro, "-", " area:", area)
